# Generated by Django 5.2.5 on 2026-05-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_reel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='hashtag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
